### ISSUE TITLE
Incorrect formula for dichlorosilane and trichlorosilane

### ISSUE THREAD

**Issue by TSrhm** [CalebBell/chemicals#45]
Hi CalebBell
The data for dichlorosilane and trichlorosilane from pubchem are outdated. Hydrogen is missing in the formula.
Sincerely,
TStrhm

**Comment by CalebBell** [comment]
Hello,
It has been quite some time but I have the scripts for adding/removing/editing chemical metadata working again (ported to python 3, working with new versions of pubchem & common chemistry integration)
I have resolved the issue. The chemical metadata for both chemicals has been resolved. It is in the new chemicals release 1.3.1. This came from a data issue in pubchem many years ago, long since resolved.
Sincerely,
Caleb
