### ISSUE TITLE
Issue with Alcock vapor pressure data

### ISSUE THREAD

**Issue by m29h** [CalebBell/chemicals#53]
**Describe the bug**
The chemical Metadata in `chemicals/Vapor Pressure/Alcock_Itkin_Horrigan_metalic_elements_sublimation.tsv` only contains parameters A, B, C, D The documentation states those parameters can be used for the [chemicals.dippr.EQ101](https://chemicals.readthedocs.io/chemicals.dippr.html#chemicals.dippr.EQ101) equation. However the EQ101 takes a fifth parameter E which default value is 0. With this default value the equation does not produce the original data published by Alcock.

When manually setting E=1 one can obtain correct values from EQ101. The easiest fix would be to change the default value of the python function code of EQ101 from 0 to 1. (not sure if this can break something else) Alternatively one could add a column with E=1 to the chemical metadata. With E=1 the above metadata seems to reproduce exactly the original publication data...

There is a second related issue in the liqud vapor pressure metadata `chemicals/Vapor Pressure/Alcock_Itkin_Horrigan_metalic_elements.tsv` In this dataset there is a column E that has the (allegedly wrong) value -3 
This makes the equation non-isomorphous to that used originally Equation by Alcock. However even when setting E=1 manually the parameters fail to reproduce (exactly) the original published data by Alcock. So maybe on this dataset something else went wrong during parameter transoformation. (the error is luckily relatively small with the pressure off within a factor of 0.5-2 or so)

**Additional context**
For most elements the difference is small so that it can be overlooked. However for Tungsten (W) the error gets HUGE when using EQ101 without manual setting E=1 on the function. (8,36e3 Pa @ 2500K) where in fact (8,05e-4 Pa would be correct)
according to Wikipedia the 10000 Pascal pressure should not be reached until about >>5000K

**bonus error**
the chemical metadata table lists a Tmin of 220 K for Tungsten. However the original Publication from Alcock has the validity of this data specified from 2200K (there is a 0 missing)

For the range from 298K to 2200K and Tungsten the original Alcock publication lists an additional parameter set which is as follows: A=-0.5570 B=-43830.0000 C=2.5145 D=-0.2074 Tmin=298 Tmax=2200 (Parameters of the original Alcock publication which uses base 10 logaritm), They would need to be transformed before being useable in EQ101.

**Comment by CalebBell** [comment]
Hi Martin,
You are correct, 1.0 as last coefficient was implied and without setting it the `D` coefficient does nothing. Thermo did use this data set, and used the 1.0 E coefficient correctly. I do hate to waste by adding a column with all the same values, but in this case I have changed the file to have the extra `E` column set to 1 anyway - it is a small file.

Regarding the temperature range for tunsten, I can confirm there was a zero missing. The 2200-2500 K range was used. The second parameter set won't be added, but someone could refit the data to cover both ranges. The higher temperature range was used because the data with a higher vapor pressure can be more accurately measured.

The -3 coefficient an error mistake, I see now the author intended for the D coefficient to be multiplied by 0.001 in the equation (and so in thermo would have a value in the .tsv 1000x less than the table). I have corrected that error. I have updated the documentation.
The improvements will be out in the next chemicals release.
